name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant gradlew execute permission
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: cs16-release-apk
          path: android/app/build/outputs/apk/release/*.apk
